---
# tasks file for ansible-role-nfs-ganesha-krb5

- name: Add repo
  when: ganesha_add_repo
  ansible.builtin.yum_repository:
    name: ganesha_repo
    description: Custom ganesha repo
    baseurl: "{{ ganesha_repo_baseurl }}"
    file: ganesha
    gpgcheck: false
- name: Install packages
  when: ganesha_install_packages
  ansible.builtin.dnf:
    name: "{{ ganesha_packages }}"
    state: installed

- name: Create config dir
  ansible.builtin.file:
    state: directory
    path: /etc/ganesha
    owner: root
    group: root
    mode: "0755"
- name: Template nfs-ganesha config
  ansible.builtin.template:
    src: ganesha.conf.j2
    dest: /etc/ganesha/ganesha.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
    lstrip_blocks: true
    # notify: Restart nfs-ganesha
