---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: aaltoscicomp.ansible_role_nfs_ganesha_krb5
      vars:
        ganesha_add_repo: true
        # Requires a custom repo with Ganesha RPMs, cannot test easily
        # ganesha_install_packages: true
        ganesha_log__components:
          - IDMAPPER: FULL_DEBUG
          - FSAL: WARN
        ganesha_exports:
          - export_id: 1
            path: /export/ganesha
            pseudo: /ganesha
            clients:
              - 192.168.0.0/16
              - 10.0.0.0/8
